select rc.TABLE_NAME, kcu.COLUMN_NAME, kcu.REFERENCED_TABLE_NAME, kcu.REFERENCED_COLUMN_NAME
from information_schema.REFERENTIAL_CONSTRAINTS rc
join information_schema.KEY_COLUMN_USAGE kcu on kcu.CONSTRAINT_NAME=rc.CONSTRAINT_NAME and kcu.TABLE_NAME=rc.TABLE_NAME and kcu.TABLE_SCHEMA=rc.CONSTRAINT_SCHEMA and kcu.TABLE_SCHEMA='{db}' and rc.TABLE_NAME = '{tbl}'